### ISSUE TITLE
Мобильная верстка

### ISSUE THREAD

**Issue by shevdi** [clicktronix/clicktronix.github.io#23]
При маленьких разрешениях окна съезжает верстка. Селект растягивается. Если скрываешь фото, то неплохо бы и текст выравнять ближе к центру.
И зеленые полоски на фоне съезжают

**Comment by clicktronix** [comment]
Поправил. А линии специально уезжают, при уменьшении масштаба, вот только там другой косяк был)) они при меньшем разрешении не пропадали, тоже поправил, не доглядел
