### ISSUE TITLE
Структура проекта

### ISSUE THREAD

**Issue by shevdi** [clicktronix/clicktronix.github.io#27]
Пока все еще структуру проекта надо улучшить.
Все для одного компонента должно лежать по сути в одной папке. В css должен быть один блок. Ни html, ни css не должны быть разбросаны по разным местам. Папка, в которой лежит блок, и сам блок должны совпадать названиями для согласованности.
Т.е. если в одной папке у тебя объявляется два разных блока, например, .form и .request-form, то это вероятно два блока и их надо разнести. Или возможно .request-form можно сделать элементом (.form__request). 

Модификаторы, которые отмечаются одним подчеркиванием, не могут применяться, если не применен элемент (например, у тебя есть такое request-form_text-input-area). На этих страницах они вероятно и не нужны.

Постарайся избегать классов не названных по бэму типа g-container.
Под @media screen стоит удалить название класса. Стилус поймет и так.

**Comment by clicktronix** [comment]
Я все поправил из этого ишью, кроме g-container'a. Прочел про использование префиксов на [сайте](https://ru.bem.info/methodology/history/#%D0%9F%D0%BE%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B1%D0%BB%D0%BE%D0%BA%D0%BE%D0%B2) БЭМа. Там используют префикс `g-` для обозначения глобального блока.
