### ISSUE TITLE
mixins

### ISSUE THREAD

**Issue by shevdi** [clicktronix/clicktronix.github.io#3]
Специальное предложение от Сергея :)
В верстке вместо простого include использовать миксины, передавая сверху вниз свойства из одного объекта.

**Comment by clicktronix** [comment]
А можно пример, как это делается? не могу разобраться немного

**Comment by shevdi** [comment]
Можешь посмотреть здесь пример здесь:
https://github.com/fullstack-development/flat-starter-kit
Заодно станет понятнее насчет структуры. 
По сути у тебя только одна страница. Посмотри demo-data.pug. Будешь также передавать вниз данные. В indipixel передавать особо нечего, а в резюме будет подгружаться много данных.

**Comment by clicktronix** [comment]
Переделал с использованием миксинов. Прикольная штука. Всё в [этом](https://github.com/clicktronix/testsummary) репозитории :)
